codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    irc:
      default:
        server: irc.freenode.net
        channel: "#fossgalaxy-dev"
        branches:
          - master
          - develop
          - feature-*
        threshold: 1.25

  status:
    project:
      default:
        target: auto
        threshold: 1.25
        branches:
          - master
          - develop
          - feature-*
    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches:
    - master
    - develop
    - feature-*
  behavior: default
